name: firebase_ml_text_recognition
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_action_sheet: ^2.0.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  google_ml_kit: ^0.7.2
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
