name: firebase_ml_text_recognition
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adaptive_action_sheet: 1.1.0
  clipboard: ^0.1.2+8

  cupertino_icons: ^1.0.0

  # Text recognition
  firebase_ml_vision: ^0.9.7
  flutter:
    sdk: flutter
  image_cropper: null
  image_picker: ^0.6.7+11
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
